/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    AppLayoutDefault: typeof import('./src/components/layout/AppLayoutDefault.vue')['default']
    AppTopbar: typeof import('./src/components/layout/AppTopbar.vue')['default']
    ChatMessage: typeof import('./src/components/chat/ChatMessage.vue')['default']
    ChatRoom: typeof import('./src/components/chat/ChatRoom.vue')['default']
    CreateRoomModal: typeof import('./src/components/chat/CreateRoomModal.vue')['default']
    RoomListItem: typeof import('./src/components/chat/RoomListItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
