/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    AppLayoutDefault: typeof import('./src/components/layout/AppLayoutDefault.vue')['default']
    AppMenuItem: typeof import('./src/components/ui/sidecar/AppMenuItem.vue')['default']
    AppPageHeader: typeof import('./src/components/layout/AppPageHeader.vue')['default']
    AppSidebar: typeof import('./src/components/ui/sidecar/AppSidebar.vue')['default']
    AppTopbar: typeof import('./src/components/layout/AppTopbar.vue')['default']
    Button: typeof import('primevue/button')['default']
    ChatMessage: typeof import('./src/components/chat/ChatMessage.vue')['default']
    ChatRoom: typeof import('./src/components/chat/ChatRoom.vue')['default']
    CreateRoomModal: typeof import('./src/components/chat/CreateRoomModal.vue')['default']
    RoomListItem: typeof import('./src/components/chat/RoomListItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
